/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user (auto-login) */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in with email + password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a refresh token for a new access token (refresh rotated) */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke a refresh token */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current authenticated user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a message or answer a clarifying question (creates a run)
         * @description Starts a new agent turn (*run*). Omit `session_id` to start a new chat.
         *
         *     Provide **either** `message`, **or** an answer to a clarifying question
         *     (`in_reply_to_question_id` plus `selected_option_ids` and/or `freeform`).
         *
         *     The response returns immediately with a `run_id`; subscribe to results by minting a
         *     stream ticket (`POST /chat/{run_id}/stream-ticket`) and opening the SSE stream.
         */
        post: operations["postChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/{run_id}/stream-ticket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mint a short-lived, single-use ticket for the SSE stream
         * @description Browser `EventSource` cannot set an `Authorization` header, so the SSE stream is authorized
         *     by a short-lived, single-use, run-scoped ticket minted here with the normal Bearer token.
         */
        post: operations["createStreamTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/{run_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream run events (Server-Sent Events)
         * @description Opens a `text/event-stream`. Authorized by the `ticket` query parameter (see
         *     `stream-ticket`). Each SSE frame has an `event:` name and a JSON `data:` payload, and
         *     carries an `id:` so a dropped connection can resume via the `Last-Event-ID` request header.
         *     The stream closes when a terminal `run_status` (`completed` / `cancelled` / `error`) is sent.
         *
         *     **Event names → data schema:**
         *     | `event:` | `data:` schema |
         *     |---|---|
         *     | `run_status` | `RunStatusEvent` |
         *     | `message_delta` | `MessageDeltaEvent` |
         *     | `message` | `MessageEvent` |
         *     | `clarifying_question` | `ClarifyingQuestionEvent` |
         *     | `plan_status` | `PlanStatusEvent` |
         *     | `map` | `MapEvent` |
         *     | `error` | `ErrorEvent` |
         *
         *     While `plan_status` is not `ready`, the frontend keeps the map read-only.
         */
        get: operations["streamRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel an in-flight run */
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the user's chats (each with a short summary of the first request) */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full message history of a chat */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the user's travel groups */
        get: operations["listGroups"];
        put?: never;
        /** Create a travel group describing all participants */
        post: operations["createGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a group with its members embedded */
        get: operations["getGroup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{group_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a group's members */
        get: operations["getGroupMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{group_id}/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preferences of every member of a group */
        get: operations["getGroupPreferences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{group_id}/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plans built for a group */
        get: operations["getGroupPlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a plan (the built route and its selected flight/hotel/tour) */
        get: operations["getPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{plan_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept a ready plan */
        post: operations["acceptPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{plan_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject a plan (terminal) */
        post: operations["rejectPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{plan_id}/modify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Correct the route — add/remove map points as a batch and rebuild
         * @description Allowed only while the plan is `ready`. Submits the user's batch of added/removed map points
         *     (plus an optional note); the plan flips back to `building` and the agent rebuilds. Subscribe
         *     to the **new** run's stream (`run_id` in the response) for the rebuild events.
         */
        post: operations["modifyPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{plan_id}/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Map points for a plan (with the editable gate)
         * @description `editable` is `true` only when `status == ready`; the frontend uses it to gate route editing.
         */
        get: operations["getPlanMap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{plan_id}/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calendar (itinerary) for a plan */
        get: operations["getPlanCalendar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /** @enum {string} */
                code: "validation_error" | "unauthorized" | "token_expired" | "forbidden" | "not_found" | "conflict" | "plan_not_ready" | "rate_limited" | "internal";
                /** @description Human-readable explanation */
                message: string;
                /** @description Optional machine-readable detail (e.g. per-field errors). */
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        RegisterRequest: {
            name: string;
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        User: {
            id: string;
            name: string;
            /** Format: email */
            email: string;
            /** Format: date-time */
            created_at: string;
        };
        TokenBundle: {
            access_token: string;
            refresh_token: string;
            /** @constant */
            token_type: "Bearer";
            /** @description Access-token lifetime in seconds */
            expires_in: number;
        };
        RegisterResponse: {
            user: components["schemas"]["User"];
            tokens: components["schemas"]["TokenBundle"];
        };
        LoginResponse: components["schemas"]["TokenBundle"] & {
            user: components["schemas"]["User"];
        };
        AccessTokenResponse: {
            access_token: string;
            /** @constant */
            token_type: "Bearer";
            expires_in: number;
            /** @description Rotated refresh token */
            refresh_token: string;
        };
        /**
         * @description Provide `message`, OR answer a clarifying question with `in_reply_to_question_id` plus
         *     `selected_option_ids` and/or `freeform`.
         */
        ChatRequest: {
            /** @description Omit to start a new chat (session). */
            session_id?: string;
            /** @description User text */
            message?: string;
            /** @description Selected travel-group context; attached to the resulting plan. */
            group_id?: string;
            /** @description Set when answering a clarifying question. */
            in_reply_to_question_id?: string;
            /** @description Chosen closed-answer option id(s). */
            selected_option_ids?: string[];
            /** @description Freeform answer when the offered options don't fit. */
            freeform?: string;
        };
        ChatAccepted: {
            run_id: string;
            session_id: string;
        };
        StreamTicket: {
            ticket: string;
            /**
             * @description Ticket lifetime in seconds
             * @example 60
             */
            expires_in: number;
        };
        CancelResponse: {
            run_id: string;
            /** @constant */
            status: "cancelling";
        };
        /** @enum {string} */
        RunStatus: "started" | "running" | "completed" | "cancelled" | "error";
        /** @enum {string} */
        PlanBuildStatus: "building" | "ready" | "error";
        MapPoint: {
            id: string;
            /** @description Settlement / point label */
            name: string;
            /** @enum {string} */
            kind: "origin" | "destination" | "stop";
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
            /** @description Position along the route (0-based) */
            order: number;
            note?: string;
        };
        QuestionOption: {
            id: string;
            label: string;
        };
        ClarifyingQuestion: {
            id: string;
            text: string;
            /** @description Mutually exclusive closed-answer options. */
            options: components["schemas"]["QuestionOption"][];
            /** @description Whether a freeform answer is accepted when no option fits. */
            allow_freeform: boolean;
        };
        RunStatusEvent: {
            run_id: string;
            status: components["schemas"]["RunStatus"];
        };
        MessageDeltaEvent: {
            run_id: string;
            message_id: string;
            /** @description Streamed assistant text chunk */
            delta: string;
        };
        MessageEvent: {
            run_id: string;
            message: components["schemas"]["Message"];
        };
        ClarifyingQuestionEvent: {
            run_id: string;
            question: components["schemas"]["ClarifyingQuestion"];
        };
        PlanStatusEvent: {
            run_id: string;
            plan_id: string;
            status: components["schemas"]["PlanBuildStatus"];
            /** @description Present when status is error */
            error?: string;
        };
        /** @description Full map snapshot (not a delta). */
        MapEvent: {
            run_id: string;
            plan_id: string;
            points: components["schemas"]["MapPoint"][];
        };
        ErrorEvent: {
            run_id: string;
            error: {
                code: string;
                message: string;
            };
        };
        /**
         * @description Union of possible SSE `data:` payloads. Discriminate on the SSE `event:` name (see the
         *     stream operation's description), not on a body field.
         */
        SseEvent: components["schemas"]["RunStatusEvent"] | components["schemas"]["MessageDeltaEvent"] | components["schemas"]["MessageEvent"] | components["schemas"]["ClarifyingQuestionEvent"] | components["schemas"]["PlanStatusEvent"] | components["schemas"]["MapEvent"] | components["schemas"]["ErrorEvent"];
        /** @description A user reply to a clarifying question. */
        Answer: {
            in_reply_to_question_id: string;
            selected_option_ids?: string[];
            freeform?: string;
        };
        PlanRef: {
            plan_id: string;
            status: components["schemas"]["PlanStatus"];
        };
        Message: {
            id: string;
            /** @enum {string} */
            role: "user" | "assistant";
            content: string;
            /** Format: date-time */
            created_at: string;
            run_id?: string;
            /** @description Present on an assistant message that asks a clarifying question. */
            question?: components["schemas"]["ClarifyingQuestion"];
            /** @description Present on a user message that answers a clarifying question. */
            answer?: components["schemas"]["Answer"];
            /** @description Present on an assistant message that (re)built a plan. */
            plan_ref?: components["schemas"]["PlanRef"];
        };
        PlanSummary: {
            plan_id: string;
            status: components["schemas"]["PlanStatus"];
            destination?: string;
            estimated_total_rub?: number;
            /** Format: date-time */
            created_at?: string;
        };
        SessionSummary: {
            id: string;
            /** @description Short summary of the first request */
            summary: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            last_message_preview?: string;
            group_id?: string;
            latest_plan_id?: string;
            plan_status?: components["schemas"]["PlanStatus"];
        };
        SessionList: {
            items: components["schemas"]["SessionSummary"][];
            total: number;
            limit: number;
            offset: number;
        };
        SessionDetail: {
            id: string;
            summary: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            group_id?: string;
            /** @description Ordered, fully reconstructable timeline. */
            messages: components["schemas"]["Message"][];
            plans: components["schemas"]["PlanSummary"][];
        };
        /** @description Mirrors traveler_preferences.csv; all fields optional/free-text. */
        PreferenceInput: {
            /** @description e.g. departure_time, hotel_rating */
            type?: string;
            value?: string;
            comment?: string;
        };
        MemberInput: {
            full_name: string;
            age?: number;
            citizenship?: string;
            home_airport?: string;
            /** @description e.g. parent, child, lead */
            role_in_group?: string;
            loyalty_program?: string;
            notes?: string;
            preferences?: components["schemas"]["PreferenceInput"][];
        };
        CreateGroupRequest: {
            name: string;
            comment?: string;
            budget_rub?: number;
            origin_city?: string;
            destination?: string;
            /** Format: date */
            start_date?: string;
            /** Format: date */
            end_date?: string;
            members: components["schemas"]["MemberInput"][];
        };
        Preference: {
            id: string;
            type?: string;
            value?: string;
            comment?: string;
        };
        Member: {
            id: string;
            full_name: string;
            age?: number;
            citizenship?: string;
            home_airport?: string;
            role_in_group?: string;
            loyalty_program?: string;
            notes?: string;
            preferences?: components["schemas"]["Preference"][];
        };
        Group: {
            id: string;
            name: string;
            comment?: string;
            budget_rub?: number;
            origin_city?: string;
            destination?: string;
            /** Format: date */
            start_date?: string;
            /** Format: date */
            end_date?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            members: components["schemas"]["Member"][];
        };
        GroupSummary: {
            id: string;
            name: string;
            comment?: string;
            budget_rub?: number;
            destination?: string;
            member_count: number;
            /** Format: date-time */
            created_at: string;
        };
        GroupList: {
            items: components["schemas"]["GroupSummary"][];
            total: number;
            limit: number;
            offset: number;
        };
        MemberList: {
            items: components["schemas"]["Member"][];
        };
        MemberPreferences: {
            member_id: string;
            full_name: string;
            preferences: components["schemas"]["Preference"][];
        };
        GroupPreferences: {
            items: components["schemas"]["MemberPreferences"][];
        };
        PlanList: {
            items: components["schemas"]["PlanSummary"][];
        };
        /** @enum {string} */
        PlanStatus: "building" | "ready" | "error" | "accepted" | "rejected";
        /** @description Mirrors flights.csv. */
        FlightSel: {
            flight_id: string;
            origin_city: string;
            destination: string;
            price_rub: number;
            baggage_included: boolean;
            stops: number;
            /**
             * @description Local HH:MM time-of-day
             * @example 10:20
             */
            departure_time: string;
            /**
             * @description Local HH:MM time-of-day
             * @example 15:40
             */
            arrival_time: string;
            /** @example standard */
            fare_type: string;
            notes?: string;
        };
        /** @description Mirrors hotels.csv; `nights` derived from the plan/recommendation. */
        HotelSel: {
            hotel_id: string;
            destination: string;
            stars: number;
            price_per_night_rub: number;
            nights: number;
            breakfast_included: boolean;
            free_cancellation: boolean;
            /**
             * Format: double
             * @example 8.7
             */
            rating: number;
            notes?: string;
        };
        /** @description Mirrors tours.csv. */
        TourSel: {
            tour_id: string;
            destination: string;
            total_price_rub: number;
            includes_flight: boolean;
            includes_transfer: boolean;
            hotel_id?: string;
            notes?: string;
        };
        /** @description The agent's selected components; any subset may be present. */
        PlanItems: {
            flight?: components["schemas"]["FlightSel"];
            hotel?: components["schemas"]["HotelSel"];
            tour?: components["schemas"]["TourSel"];
        };
        Plan: {
            id: string;
            session_id: string;
            group_id?: string;
            run_id: string;
            status: components["schemas"]["PlanStatus"];
            summary?: string;
            destination?: string;
            /** Format: date */
            start_date?: string;
            /** Format: date */
            end_date?: string;
            /** @description Why the agent chose these components (from *_recommendations.csv). */
            decision_rationale?: string;
            estimated_total_rub?: number;
            items: components["schemas"]["PlanItems"];
            map_points: components["schemas"]["MapPoint"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        RejectRequest: {
            reason?: string;
        };
        AddPoint: {
            name: string;
            /** @enum {string} */
            kind?: "origin" | "destination" | "stop";
            /** Format: double */
            lat?: number;
            /** Format: double */
            lng?: number;
            /** @description Insert after this existing point (route ordering hint). */
            after_point_id?: string;
        };
        /** @description Batch route correction. The plan must be `ready`. */
        ModifyRequest: {
            add?: components["schemas"]["AddPoint"][];
            /** @description Ids of map points to remove. */
            remove?: string[];
            /** @description Free-text wishes for the rebuild. */
            note?: string;
        };
        ModifyAccepted: {
            /** @description The rebuild run to stream. */
            run_id: string;
        };
        MapBounds: {
            /** Format: double */
            north: number;
            /** Format: double */
            south: number;
            /** Format: double */
            east: number;
            /** Format: double */
            west: number;
        };
        PlanMap: {
            plan_id: string;
            status: components["schemas"]["PlanStatus"];
            /** @description True only when status == ready; gates frontend editing. */
            editable: boolean;
            points: components["schemas"]["MapPoint"][];
            bounds?: components["schemas"]["MapBounds"];
        };
        CalendarEvent: {
            id: string;
            /** @enum {string} */
            type: "flight" | "hotel" | "tour" | "activity";
            title: string;
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end?: string;
            location?: string;
            /** @description Id of the related flight/hotel/tour, when applicable. */
            ref_id?: string;
            notes?: string;
        };
        PlanCalendar: {
            plan_id: string;
            /** @description IANA tz name, e.g. Europe/Moscow */
            timezone?: string;
            events: components["schemas"]["CalendarEvent"][];
        };
    };
    responses: {
        /** @description Missing/invalid token, or token expired */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authenticated but not allowed */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unknown resource */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Conflict (e.g. email already registered) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Modify/accept attempted while the plan is not `ready` */
        PlanNotReady: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Malformed or invalid body/params */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many requests */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Limit: number;
        Offset: number;
        RunId: string;
        SessionId: string;
        GroupId: string;
        PlanId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Created and logged in */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description New access token (and rotated refresh token) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessTokenResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Refresh token revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    postChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Run accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatAccepted"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    createStreamTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stream ticket */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamTicket"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    streamRun: {
        parameters: {
            query: {
                /** @description One-time stream ticket from `POST /chat/{run_id}/stream-ticket`. */
                ticket: string;
            };
            header?: {
                /** @description Resume the stream after this event id (set automatically by `EventSource`). */
                "Last-Event-ID"?: string;
            };
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description An event stream. The schema below documents the union of possible `data:` payloads;
             *     use the `event:` name to discriminate (see the table above).
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEvent"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation requested */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Run already finished */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listSessions: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated chat list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The chat with its ordered messages and plan summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listGroups: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated group list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGroupRequest"];
            };
        };
        responses: {
            /** @description Created group (members embedded) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
        };
    };
    getGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The group */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getGroupMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Members of the group */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getGroupPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Preferences grouped by member */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupPreferences"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getGroupPlans: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plan summaries for the group */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: components["parameters"]["PlanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    acceptPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: components["parameters"]["PlanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plan accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["PlanNotReady"];
        };
    };
    rejectPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: components["parameters"]["PlanId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RejectRequest"];
            };
        };
        responses: {
            /** @description Plan rejected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    modifyPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: components["parameters"]["PlanId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModifyRequest"];
            };
        };
        responses: {
            /** @description Rebuild started on a new run */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModifyAccepted"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["PlanNotReady"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    getPlanMap: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: components["parameters"]["PlanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Map snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanMap"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getPlanCalendar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: components["parameters"]["PlanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Calendar events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanCalendar"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
